apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvvol-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  #storageClassName: standard
  nfs:
    path: /opt/postgres
    server: 172.81.180.115
    readOnly: false
