apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  type: NodePort
  ports:
    - name: "20100"
      port: 20100
      targetPort: 80
      nodePort: 30100
  selector:
    io.kompose.service: pgadmin

