apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: todoapplication-postgres
  name: todoapplication-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: todoapplication-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.network/lan_network: "true"
        io.kompose.service: todoapplication-postgres
    spec:
      containers:
        - image: systemdevformations/todoapplication-postgres
          name: todoapplication-postgres
          ports:
            - containerPort: 5000
          resources: {}
      hostname: todo
      restartPolicy: Always

